### ISSUE TITLE
delete this repo

### ISSUE THREAD

**Issue by josephdadams** [bitfocus/companion-module-novastar-vx4s#5]
@krocheck I recommend we delete this repo in favor of the broader module repo. It is still referenced as a submodule so that will need to be removed and the broader module should be included in core.

**Comment by krocheck** [comment]
I don't know that I've seen confirmation the new one works.  I'll have to check compatibility and possibly write an upgrade script to move these users over.

**Comment by McHauge** [comment]
got a person on FB that had some trouble with this module but the other/new module works for them with a VX4S unit

primarily with the blackout and back to normal button

**Comment by McHauge** [comment]
just got an update from Ralf Girnstein with the new module:

Andreas Hauge Thomsen everything is running, except for the "test pattern", the colors are not correct there and only the first port is used. whereby all ports are operated via the controller.
